# 单点登录桥接配置   SINGLE_SIGN_ON
SINGLE_SIGN_ON_IP = "http://192.168.0.113"
SINGLE_SIGN_ON_PORT = "8008"
SINGLE_SIGN_ON_BASE = SINGLE_SIGN_ON_IP+":"+SINGLE_SIGN_ON_PORT
SINGLE_SIGN_ON_USER = SINGLE_SIGN_ON_BASE+"/users"
SINGLE_SIGN_ON_CODE = SINGLE_SIGN_ON_BASE+"/code"